### ISSUE TITLE
data "not found"

### ISSUE THREAD

**Issue by spono** [gtergeomatica/chm_from_lidar#10]
Hi,
using the plugin I get opnly the tile index vector file while I'm unable to download the CHM products due to the following error:

```
Processing tile n. 1 of 101

The DSM file is: \\rvphnas02pw\Remote_Sensing\Lidar\2010_Lidar_Etra\14_Digital_Surface_Model_GB-FO\ASCII_XYZ_1m\dsm_etra_0637.asc

The DTM file is: \\rvphnas02pw\Remote_Sensing\Lidar\2010_Lidar_Etra\15_Digital_Terrain_Model_GB-FO\ASCII_XYZ_1m\dtm_etra_0637.asc

WARNING: DSM file dsm_etra_0637.asc and DTM file dtm_etra_0637.asc not found. The related CHM will not be computed.
```

Might it be an issue related to the data provider or what?
Thanks in advance

**Comment by rmarzocchi84** [comment]
it seems a problem with input data:

1) have you the two input file in the correct directory?

2) the directory is accessible for QGIS? try to open the file in QGIS using the path you read \\rvphnas02pw\Remote_Sensing\Lidar\2010_Lidar_Etra\...

**Comment by spono** [comment]
within the local folder there is only the vector file with tiles but not the 101x2 ASCII files: it seems that the download does not take place.

I guess `\\rvphnas02pw\Remote_Sensing\Lidar\2010_Lidar_Etra\14_Digital_Surface_Model_GB-FO\ASCII_XYZ_1m\` is the server path from which it should be downloaded

**Comment by rmarzocchi84** [comment]
Sorry I do not understand the first question and I quickly answer.
The plugin you are using do not download original raster data. The vector layer is only an example of how it can works. It is the vector we have created for Regione Veneto which founded the plugin.
You can create your vector layer with your raster data using the  plugin Lidar Tile Maker: https://lidar-tile-maker-manuale.readthedocs.io/en/latest/

If you do not have raster data (DTM and DSM) you can find it on the official website of your region/country etc,
