### ISSUE TITLE
prova dati ETRA

### ISSUE THREAD

**Issue by sergiozenforeste** [gtergeomatica/chm_from_lidar#3]
Sto provando il plugin con i dati di etra.
Seleziono la AOI relativa la comune di Campolongo sul brenta, selziono l'ente ETRA, seleziono la campagna, imposto gli altri dati e lancio l'elaborazone.
Vengono estratte le tiles come vedi nell'immagine sottostante, 
L'errore python è evidenziato nell'immagine sottostante.

![immagine](https://user-images.githubusercontent.com/52998256/61362690-e4d6ad80-a882-11e9-9dd0-d65d15431d38.png)

ho veriricato il percorso che è corretto:
\\rvphnas02pw\Remote_Sensing\Lidar\2010_Lidar_Etra\15_Digital_Terrain_Model_GB-FO\ASCII_XYZ_1m
ed i files sono presenti nella cartella.

Sergio Zen

**Comment by RobiFag** [comment]
Ciao Sergio,
ma vi ha dato un errore python (banda gialla nella schermata qgis)? il processo è terminato o si è bloccato?

**Comment by sergiozenforeste** [comment]
si è bloccato.

Il giorno mer 17 lug 2019 alle ore 11:21 RobiFag <notifications@github.com>
ha scritto:

**Comment by DanieleSav** [comment]
Ho il sospetto che nel caso in questione, il problema non sia dovuto al percorso errato o al nome del file errato, ma all'estensione non appropriata. Credo che dietro questi files ASC si nascondano degli XYZ. Per generare manualmente i CHM di questo volo ricordo che ero partito non dal DTM e DSM, ma dal dato grezzo (LAS), proprio perché avevo incontrato problemi con quegli "ASC" anomali.
E' un'ipotesi da verificare.

**Comment by RobiFag** [comment]
Ci puoi mandare un dtm e il relativo dsm per poter fare una prova?

**Comment by DanieleSav** [comment]
[esempio_DTM_DSM_ETRA.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3401113/esempio_DTM_DSM_ETRA.zip)

**Comment by rmarzocchi84** [comment]
grazie! abbiamo effettivamente verificato che il formato dei dati è una sorta di XYZ e anche in questo caso il CRS è 3003 e non 4326. Cerchiamo un modo di aprire i file e vi aggiorniamo, dopdichè anche questo è un problema indipendente dal plugin

**Comment by rmarzocchi84** [comment]
Confermiamo quanto scritto sopra.

Si tratta di vari problemi sui dati di input (DSM e DTM):

* formato vettoriale (tipo XYZ ma file di testo non standard, con QGIS lo devi aprire con "importa file di testo.." per cui sono inutilizzabili come input di qualsiasi plugin che richieda dati raster in input)
* CRS indicato in tabella errato (come anche per l'altra campagna https://github.com/gtergeomatica/chm_from_lidar/issues/4 )

Già che ci siamo per farvi capire cosa fosse il problema abbiamo creato questo script GRASS che abbiamo realizzato e testato per la conversione dei dati in formato raster: Lo script sarebbe lo dovreste modificare e usare su tutta la vostra campagna per convertire i dati da vettore a raster  
[script_conversione_grass.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3402004/script_conversione_grass.zip)



Dopodichè direi che dovremmo usare le issues per problematiche legate al plugin e non ai dati. Quindi in casi come questo dovreste verificare prima i dati e aprire la issue solo una volta verificato il problema (che non dipende dal plugin) per richiedere il cambio di attrributi sul  file con le tiles 

Ad esempio in questo caso la issue corretta avrebbe dovuto essere: 

* TITOLO ISSUE: campagna dati ETRA CRS indicato in tabella sbagliato
* CONTENUTO: modificare CRS da 4326 a 3003

Altrimenti non avendo la possibilità di vedere i vostri dati rischiamo di impantanare tutte le procedure di debug perdendo tempo inutile.
