### ISSUE TITLE
Correzione CRS dati ETRA

### ISSUE THREAD

**Issue by rmarzocchi84** [gtergeomatica/chm_from_lidar#5]
Come da issue https://github.com/gtergeomatica/chm_from_lidar/issues/3 va corretto il sistema di riferimento nella tabella con le tile da 4326 a 3003. 

Si richiede a Regione di verificare se questo è vero per tutte le tiles di dati ETRA

**Comment by RobiFag** [comment]
Modificato l'EPSG per l'inter campagna da 4326 a 3003.
@sergiozenforeste
