### ISSUE TITLE
volo lidar comuni di san pietro e santo stefano

### ISSUE THREAD

**Issue by sergiozenforeste** [gtergeomatica/chm_from_lidar#6]
Ho provato ad utililizzare i dati del volo LIDAR san pietro e santo stefano.
nello shape comuni ho selezionato il comune di sanPietro,
ho lanciato il plugin indicando l'area di interesse lo shape dei comuni, e flaggando solo geometrie selzionate, compare come ente il solo volo lidar, 
seleziono la sola campagna san pietro e santo stefano
seleziono gli altri parametri, nome clip, cartella lavoro e CRS ma il plugin mi informa che non vi è alcuna tiles per l'area selzionata.

![immagine](https://user-images.githubusercontent.com/52998256/61699716-b736ac00-ad3b-11e9-88e2-9b43398ed372.png)

ho provato con la funzione di intersezione di QGIS utilizzando i medesimi parametri e viene generato lo shape di intersezione come da successiva immagine.

![immagine](https://user-images.githubusercontent.com/52998256/61699897-0e3c8100-ad3c-11e9-99d0-f901e0ddb5d7.png)

**Comment by RobiFag** [comment]
Ciao Sergio,
nel file tile_dsm_dtm non mi risulta una campagna Lidar_Pietr_Cadore_S_Stefano, che file state utilizzando per le tile? Nel caso me lo puoi inviare per fare due test?
Altra domanda, il file delle tile ha lo stesso sistema di riferimento del file dei comuni?

**Comment by DanieleSav** [comment]
Lo stesso problema evidenziato da Sergio si verifica anche per COMUNE_PADOVA, campagna di volo 2007_Lidar_Comune_Padova

**Comment by rmarzocchi84** [comment]
Il problema è che per quelle campagne manca o DTM o DSM (ricordo che avevamo visto il problema con @sergiozenforeste durante il corso per la campagna di Padova).

A tal proposito abbiamo messo un filtro sul file delle tile che carica solo quelle dove c'è contemporaneamente DTM e DSM. Evidentemente avete rimosso quel filtro. 

In ogni caso ci viene bene questo test perché ci dice che bisogna specificare meglio il messaggio di errore. Non avevamo considerato che l'utente potesse rimuovere il filtro, ma effettivamente è una casistica possibile.

**Comment by DanieleSav** [comment]
Confermo. Avevamo rimosso il filtro "N_DTM" NOT NULL and "N_DSM" NOT NULL

**Comment by RobiFag** [comment]
Modificato messaggio di log nel caso in cui venga selezionata una campagna per la quale non sono presenti Dtm o Dsm. Si consiglia comunque di non rimuovere il filtro.
