### ISSUE TITLE
Verifica CRS

### ISSUE THREAD

**Issue by RobiFag** [gtergeomatica/chm_from_lidar#7]
Correggendo i codici EPSG per le campagne ETRA #5  e Lidar_delta_Po #4 ci siamo resi conto che altre campagne potrebbero avere un sistema di riferimento diverso da quanto scritto nella colo SR_EPSG della tabella. Di seguito l'elenco delle campagne che vi chiediamo di verificare così da correggere eventualmente anche i codici di queste:
Costa Veneta Genio Civile
Costa Veneta Consorzio Venezia Nuova
Lidar Costa Delta
LidarMATTM/contratto 204
Lidar Costa Rovigo

Queste campagne hanno tutte riferimenti a CRS diversi nei nomi delle cartelle che compongono i percorsi ai file mentre il codice EPSG in tabella è il 4326.

**Comment by rmarzocchi84** [comment]
@sergiozenforeste e/o @DanieleSav ci confermate? così prima di sottomettere nuova versione sistemiamo anche questo

**Comment by DanieleSav** [comment]
[MATTM_Contratto204.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3421885/MATTM_Contratto204.zip)
[CostaVenetaConsorzioVeneziaNuova.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3421886/CostaVenetaConsorzioVeneziaNuova.zip)
[CostaVenetaGenioCivile.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3421887/CostaVenetaGenioCivile.zip)
[LidarCostaDelta.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3421888/LidarCostaDelta.zip)

Costa Veneta Genio Civile
Costa Veneta Consorzio Venezia Nuova
Lidar Costa Delta
dovrebbero essere EPSG 3003, Contratto 204 non lo so. Se riesci, verifica anche tu nei files di esempio che ti ho mandato (uno per volo, ad eccezione di Costa Rovigo che ho omesso essendo un xyz).

**Comment by rmarzocchi84** [comment]
Costa Veneta Genio Civile
Costa Veneta Consorzio Venezia Nuova
Lidar Costa Delta

sono chiaramente 3003

 MATTM_Contratto204 è chiaramente un sistema geografico non proiettato, però siccome nel nome della cartella c'è scritto etrf89 potrebbe non essere 4326, ma un altro sistema... es. RDN2008?  però è difficile verificare. Non avete nessun file o relazione che vi sia stato consegnato assieme ai dati raster

Costa Rovigo sono file xyz ma se volete nel frattempo sistemiamo il CRS così almeno quello è fatto in attesa di convertire i file

**Comment by RobiFag** [comment]
Per quanto riguarda:
Costa Veneta Genio Civile
Costa Veneta Consorzio Venezia Nuova
Lidar Costa Delta

è stato modificato il codice epsg da 4326 a 3003

**Comment by DanieleSav** [comment]
L'intuizione su MATTM_contratto204 è corretta. Rovistando nel disco di rete, infatti, ho trovato i metadati che confermano trattarsi di EPSG 6706 (RDN2008). 
Allego alcuni esempi di metadato, oltre ad uno degli xyz di Costa Rovigo.

[metadati_MATTM_contratto204.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3425345/metadati_MATTM_contratto204.zip)
[costa_rovigo_dtm.zip](https://github.com/gtergeomatica/chm_from_lidar/files/3425398/costa_rovigo_dtm.zip)

**Comment by RobiFag** [comment]
abbiamo modificato il codice epsg della campagna MATTM_contratto204 da 4326 a 6706 e quello della campagna Lidar Costa Rovigo da 4326 a 3003.

**Comment by rmarzocchi84** [comment]
Come promesso a @sergiozenforeste ho fatto alcune verifiche sui file XYZ:

* il formato XYZ è effettivamente un formato gdal standard ma si aspetta che i dati siano ordinati per la colonna Y  e X, inoltre le Y e le X dovrebbero essere sempre le stesse invece  anche provando a riordinare mi sembra che ai decimali ci siano delle differenze millimetriche probabilmente dovute a traformazioni di CRS che però non piacciono a GDAL: in sostanza non è una griglia regolare
* per convertire i dati xyz con qgis la procedura consta di pochi passaggi ma è piuttosto noiosa e difficilmente automatizzabile (ho fatto un po' di ricerche se fosse possibile usare il modellatore grafico, ma direi nulla di fatto):
    1) si tratta di aprire il file come file di testo delimitato 
    2) esportare il vettoriale corrispondente
    3) e una volta esportato il vettoriale rasterizzare il risultato.  
* il problema è che questa procedura temo vada fatta file per file

**Comment by rmarzocchi84** [comment]
in ogni caso problemi CRS risolti quindi issue chiusa

**Comment by DanieleSav** [comment]
Per gli xyz penso convenga procedere ad una conversione in batch in formato asc o tif utilizzando altri software oppure, per il volo ETRA, utilizzare i tif dei DTM e DSM che ho generato io partendo dal las.

**Comment by RobiFag** [comment]
Ok, ricordatevi solo di comunicarci i nuovi percorsi e i nuovi nomi dei file (soprattutto l'estensione) così da aggiornare il file delle tile.

**Comment by sergiozenforeste** [comment]
Ti ricordo di correggere l'errore letterale presente nella maschera del
plugin *seleziona area intresse:*

Ti suggerisco se possibile di riportare nel log un indicazione della tile
in fase di elaborazione dato che avendo acquisito la numerosità delle tiles
posso dare una informazione sullo stato di avanzamnto della elaborazione.

*Ti ricordo inoltre che nel contrato era stato indicato di** realizzare e
caricare sul canale YouTube di Gter di un video tutorial che descriva
l’utilizzo del*
* plugin implementato, penso che possiate utilizzare i dati che vi ho
fornito realtivi all'area di Cortina.*


*Sergio Zen *

Il giorno gio 25 lug 2019 alle ore 11:50 RobiFag <notifications@github.com>
ha scritto:

**Comment by RobiFag** [comment]
si hai ragione mi era sfuggito il refuso nell'ultima versione, l'ho già corretto è sarà visibile dalla prossima versione. 

Per quanto riguarda il log, cosa intendi per indicazione della tile? il conteggio?

**Comment by sergiozenforeste** [comment]
Nel caso di selezione della AOI viene effettuata una intersezione con il layer tile_dst_dtm che genera un layer contenete le tiles ricadenti nella AOI. Questo numero è utilizzato per eseguiro il ciclo che porta alla elaborazione dei CHM. Trattandosi di un ciclo posso informare l'utente nel log che il plugin sta elaborando la tile 1 su 10, completata l'elaborazione di questa, prosegue il ciclo e informa l'utente che sta eseguendo l'elaborazione della tile 2 su 10, questo fino alla 10 tile.
In caso di utilizzo di procedure batch, QGIS fornisce nel log un messaggio, aggiornato ad ogni step, della riga eseguita.

**Comment by RobiFag** [comment]
ok fatto, sarà ovviamente disponibile dalla prossima release.

**Comment by rmarzocchi84** [comment]
Sottometto una nuova release oggi pomeriggio in maniera che lunedì ve la possiate ri-trovare con i vari aggiustamenti, se ci fossero altre annotazioni / correzioni fatecele avere . 

Facciamo anche un video di presentazione del tutorial che carichiamo sul canale youtube e aggiungiamo al tutorial già realizzato.

**Comment by rmarzocchi84** [comment]
Link al videotutorial: https://www.youtube.com/watch?v=dZ-jwO-p0Uk lo aggiungeremo anche a tutorial e manuale.

**Comment by DanieleSav** [comment]
Ottimo e utile anche il riferimento al secondo plugin "Lidar tile maker"!
Per quanto riguarda la prima parte del tutorial, dedicata a "CHM from Lidar" ho notato che non si illustra la scelta del CRS e, soprattutto, non si lancia l'elaborazione. Mi sembrerebbe carino oltre che opportuno far vedere anche il risultato finale, considerato che l'AOI è piccolina e i tempi di elaborazione veloci.

**Comment by rmarzocchi84** [comment]
> Ottimo e utile anche il riferimento al secondo plugin "Lidar tile maker"!

Questo crediamo sia un importante valore aggiunto.

> Per quanto riguarda la prima parte del tutorial, dedicata a "CHM from Lidar" ho notato che non si illustra la scelta del CRS e, soprattutto, non si lancia l'elaborazione. Mi sembrerebbe carino oltre che opportuno far vedere anche il risultato finale, considerato che l'AOI è piccolina e i tempi di elaborazione veloci.

Sì in realtà tutta la casistica è ampiamente spiegata nel tutorial scritto a cui rimandiamo in calce al video. In ogni caso se mai potremmo integrare in futuro con video specifici dei singoli casi (AOI, campagna, etc). Credo che questo video sia già eccessivamente lungo per mantenere desta l'attenzione degli utenti.
